# Math Foundations – Linear Algebra (Part 2)

---
---

## Task 1 Matrix Multiplication Rules:


### Definition

- Matrix multiplication combines two matrices to produce a new matrix. It’s a core operation in AI/ML, used in neural network layers (e.g., weight matrices × input vectors).

- Notation: For matrices $ A $ (size $ m \times n $) and $ B $ (size $ n \times p $), the product $ C = A \cdot B $ is a matrix of size $ m \times p $.

### Rules

1. Dimension Compatibility:

    - The number of columns in $ A $ ($ n $) must equal the number of rows in $ B $ ($ n $).
    - Resulting matrix $ C $ has dimensions $ m \times p $.

2. Element Calculation:

    = Each element $ C_{ij} $ in the resulting matrix is the dot product of the $ i $-th row of $ A $ and the $ j $-th column of $ B $:
$$C_{ij} = \sum_{k=1}^n A_{ik} \cdot B_{kj}$$

3. Non-Commutative:

    - Matrix multiplication is not commutative: $ A \cdot B \neq B \cdot A $ (in general).

4. Associative and Distributive:

    - Associative: $ (A \cdot B) \cdot C = A \cdot (B \cdot C) $.
    - Distributive: $ A \cdot (B + C) = A \cdot B + A \cdot C $.

### Example

- Matrices:
$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \text{(2×2)}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} \text{(2×2)}$$

- Product $ C = A \cdot B $
$$C = \begin{bmatrix} (1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\ (3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8) \end{bmatrix} = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$$

### AI/ML Relevance

- Matrix multiplication is used in neural networks to compute weighted sums (e.g., input × weights) and in transformations like rotations or scaling in computer vision.

### Python Implementation

- Use NumPy’s np.dot() or @ operator for matrix multiplication.

In [2]:
import numpy as np

# Define the Martices

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

C = np.dot(A,B)
C

array([[19, 22],
       [43, 50]])

---
---
## Task 2: Transpose of Matrix

### Definition

- The transpose of a matrix $ A $, denoted $ A^T $, swaps its rows and columns. If $ A $ is $ m \times n $, then $ A^T $ is $ n \times m $.
- Rule: For element $ A_{ij} $ in the original matrix, the transposed element is $ A^T_{ji} $.

### Properties

- $ (A^T)^T = A $: Transposing twice returns the original matrix.
- $ (A + B)^T = A^T + B^T $: Transpose of a sum is the sum of transposes.
- $ (A \cdot B)^T = B^T \cdot A^T $: Transpose of a product reverses the order.

### Example

- Matrix:
$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \text{(2×3)}$$

- Transpose:
$$A^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix} \text{(3×2)}$$

### AI/ML Relevance

- Transposes are used in ML for operations like computing gradients, adjusting data formats, or in attention mechanisms (e.g., transformers in NLP).

### Python Implementation

Use NumPy’s .T attribute or np.transpose().

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
A_T = A.T

print("Matrix A:")
print(A)
print("\nTranspose A^T:")
print(A_T)

Matrix A:
[[1 2 3]
 [4 5 6]]

Transpose A^T:
[[1 4]
 [2 5]
 [3 6]]


---
---

## Task 3: Identity & Inverse Matrix Intuition

### Identity Matrix

- Definition: An identity matrix $ I $ is a square matrix (same number of rows and columns) with 1s on the main diagonal and 0s elsewhere. It acts like the number 1 in matrix multiplication.

- Notation: Denoted $ I_n $ for an $ n \times n $ matrix.
Example (2×2):
$$I_2 = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$

- Property: For any matrix $ A $ (size $ m \times n $), $ A \cdot I_n = A $ and $ I_m \cdot A = A $.

- Intuition: It’s a “do-nothing” matrix, leaving the original matrix unchanged when multiplied (like multiplying a number by 1).

- AI/ML Relevance: Used in initializing weights or solving linear systems in optimization.

### Inverse Matrix

- Definition: For a square matrix $ A $, its inverse $ A^{-1} $ (if it exists) satisfies:
$$A \cdot A^{-1} = I \quad \text{and} \quad A^{-1} \cdot A = I$$

- Conditions:

    - $ A $ must be square.
    - $ A $ must be invertible (non-singular, i.e., its determinant $ \det(A) \neq 0 $).


- Example (2×2 matrix):
    - $$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$

    - Determinant: $ \det(A) = (1 \cdot 4) - (2 \cdot 3) = 4 - 6 = -2 \neq 0 $, so invertible.
    
    - Inverse formula for 2×2 matrix $ \begin{bmatrix} a & b \\ c & d \end{bmatrix} $:
$$A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$
$$A^{-1} = \frac{1}{-2} \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}$$

- Intuition: The inverse “undoes” the transformation of $ A $. If $ A $ scales or rotates a vector, $ A^{-1} $ reverses it.

- AI/ML Relevance: Used in solving linear systems (e.g., least squares in regression) or computing gradients in optimization.


### Python Implementation

- Use np.eye() for identity matrix and np.linalg.inv() for inverse.

In [6]:
import numpy as np

# Identity Matrix
I = np.eye(2)
print(f'Itentity Matrix => {I}')

# Inverse Matrix
A = np.array([[1,2], [3,4]])

try:
    A_inv = np.linalg.inv(A)
    print("\nMatrix A:")
    print(A)
    print("\nInverse A^-1:")
    print(A_inv)
    print("\nVerification (A · A^-1 = I):")
    print(np.dot(A, A_inv))  # Should be close to identity
except np.linalg.LinAlgError:
    print("Matrix is not invertible")

Itentity Matrix => [[1. 0.]
 [0. 1.]]

Matrix A:
[[1 2]
 [3 4]]

Inverse A^-1:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A · A^-1 = I):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


---
---
## Project: Matrix Transformer

### Project Description

- Input: A matrix (2D list of numbers).
- Output:

    - The transpose of the matrix.
    - The matrix multiplied by a scalar (e.g., 2).

- Implementation: Use NumPy to compute the transpose and scalar multiplication, with error handling for invalid inputs.

- Steps

    - Convert the input 2D list to a NumPy array.
    - Compute the transpose using .T or np.transpose().
    - Perform scalar multiplication with a chosen scalar (e.g., 2).
    - Return and display both results.

In [15]:
import numpy as np

def matrix_transformer(matrix, scalar=2):
    # Step 1: Convert input 2D list to array
    try:
        A = np.array(matrix, dtype=float)
        print(f'\n{A}\n')
        if A.ndim != 2:
            raise ValueError("Input Must be 2D Matrix")
    except:
        raise ValueError('Invalid Matrix Input')
        
    # Step 2: Compute Transpose
    A_T = A.T
    
    # Step 3: Perform Scaler Multiplication
    A_Scaler = scalar * A

    return A_T, A_Scaler

# Example Usage
try:
    input_matrix = [[1,2,3], [4,5,6]]
    transpose, scaled = matrix_transformer(input_matrix, scalar=2)
    
    print("Input Matrix:")
    print(np.array(input_matrix))
    print("\nTranspose:")
    print(transpose)
    print("\nScalar Multiplication (scalar = 2):")
    print(scaled)
    
except ValueError as e:
    print(f"Error: {e}")


[[1 2 3]
 [4 5 6]]

Input Matrix:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]

Scalar Multiplication (scalar = 2):
[[ 2  4  6]
 [ 8 10 12]]
