# Math Foundations – Linear Algebra (Part 1)

---
---

## Task 1: Scalars, Vectors, Matrices Basics

### Scalars

- Definition: A scalar is a single number, representing a quantity with magnitude but no direction. It’s a 0-dimensional entity.

- Examples:

    - A temperature reading: 25 (e.g., 25°C).
    - A learning rate in ML: 0.01.
    - Any real number (integer, float, etc.), like 3, -7.5, or π.

- Role in AI/ML: Scalars are used for parameters (e.g., weights in neural networks) or loss values.

### Vectors

- Definition: A vector is an ordered list of numbers (scalars), representing a quantity with magnitude and direction. It’s a 1-dimensional array, often visualized as a point in space or an arrow.

- Examples:

    - A 2D vector: [3, 4] (e.g., representing a point in a 2D plane).
    - A feature vector in ML: [0.5, 1.2, 3.7] (e.g., representing features like height, weight, age).

- Notation: Written as a column or row, e.g.,
$$\vec{v} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} \text{(column vector)} \quad \text{or} \quad \vec{v} = [3, 4] \text{(row vector)}.$$

- Role in AI/ML: Vectors represent data points, model weights, or gradients in algorithms like gradient descent.

### Matrices

- Definition: A matrix is a 2-dimensional array of numbers, organized in rows and columns. It’s used to represent relationships or transformations.
- Examples:

    - A 2x3 matrix (2 rows, 3 columns):
$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

    - An image in ML: A 28x28 grayscale image can be a 28x28 matrix of pixel intensities.

- Notation: Denoted as $ A_{m \times n} $, where $ m $ is the number of rows and $ n $ is the number of columns.

- Role in AI/ML: Matrices represent datasets, weight matrices in neural networks, or transformations (e.g., rotations in image processing).

### Intuition

- Scalar: A single value, like a weight or score.
- Vector: A list of values, like coordinates or features of a data point.
- Matrix: A grid of values, like a table of data or a neural network layer’s weights.
- In ML, datasets are often matrices (rows = samples, columns = features), vectors are individual data points, and scalars are used for calculations like loss or learning rates.


---
---

## Task 2: Matrix Addition, Scalar Multiplication


### Matrix Addition

- Adding two matrices involves adding their corresponding elements. Matrices must have the same dimensions (same number of rows and columns).

- Rule: For matrices $ A $ and $ B $, both of size $ m \times n $, the sum $ C = A + B $ is:
$$C_{ij} = A_{ij} + B_{ij}$$
where $ C_{ij} $ is the element in the $ i $-th row and $ j $-th column.

- Example:
$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$$
$$A + B = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}$$

- Role in AI/ML: Used in operations like combining feature matrices or updating weights in neural networks.

#### Python Implementation: Use NumPy’s np.array for matrices and the + operator for addition.

- Steps:

    - Import NumPy to handle matrix operations.
    - Define two matrices of the same dimensions as NumPy arrays.
    - Use the + operator or np.add() to add the matrices.
    - Display the result.

In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 44.9 kB/s eta 0:00:00m eta 0:00:030:12:15


In [3]:
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

C = A + B
C

array([[ 6,  8],
       [10, 12]])

### Scalar Multiplication

- Multiplying a matrix by a scalar involves multiplying every element of the matrix by that scalar.
- Rule: For a scalar $ k $ and matrix $ A $, the result $ C = kA $ is:
$$C_{ij} = k \cdot A_{ij}$$

- Example:
$$k = 2, \quad A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$
$$kA = 2 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 2 \cdot 1 & 2 \cdot 2 \\ 2 \cdot 3 & 2 \cdot 4 \end{bmatrix} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}$$

- Role in AI/ML: Scalar multiplication scales weights or features, often used in optimization (e.g., scaling gradients in gradient descent).



In [4]:
import numpy as np

# Step 1: Define a matrix and a scalar
A = np.array([[1, 2], [3, 4]])
k = 2

# Step 2: Perform scalar multiplication
C = k * A  # or use np.multiply(k, A)

# Step 3: Print the matrix and result
print("Matrix A:")
print(A)
print("\nScalar k:", k)
print("\nk * A:")
print(C)

Matrix A:
[[1 2]
 [3 4]]

Scalar k: 2

k * A:
[[2 4]
 [6 8]]


### Key Notes

- Matrix addition requires matching dimensions; otherwise, it’s undefined.
- Scalar multiplication works with any matrix size, as it’s just element-wise scaling.
- These operations are foundational for manipulating data in ML algorithms.

---
---

## Task 3: Dot Product Intuition

### Definition

- The dot product is an operation between two vectors of the same length, producing a scalar. It measures how aligned or similar two vectors are.

- Formula: For vectors $ \vec{a} = [a_1, a_2, \dots, a_n] $ and $ \vec{b} = [b_1, b_2, \dots, b_n] $, the dot product is:
$$\vec{a} \cdot \vec{b} = a_1 b_1 + a_2 b_2 + \dots + a_n b_n$$

- Example:
$$\vec{a} = [1, 2, 3], \quad \vec{b} = [4, 5, 6]$$
$$\vec{a} \cdot \vec{b} = (1 \cdot 4) + (2 \cdot 5) + (3 \cdot 6) = 4 + 10 + 18 = 32$$

### Geometric Intuition

- The dot product reflects the similarity or alignment between two vectors:

    - If the vectors point in similar directions, the dot product is positive and large.
    - If they’re perpendicular (orthogonal), the dot product is zero.
    - If they point in opposite directions, the dot product is negative.


- Mathematically:
$$\vec{a} \cdot \vec{b} = \|\vec{a}\| \|\vec{b}\| \cos(\theta)$$
where $ \|\vec{a}\| $ and $ \|\vec{b}\| $ are the magnitudes (lengths) of the vectors, and $ \theta $ is the angle between them.


- Example Visualization:

    - For $ \vec{a} = [1, 0] $, $ \vec{b} = [0, 1] $ (perpendicular vectors):
$$\vec{a} \cdot \vec{b} = (1 \cdot 0) + (0 \cdot 1) = 0$$
    - This confirms they’re orthogonal (angle = 90°).

### Role in AI/ML

- Neural Networks: The dot product is used in computing weighted sums (e.g., input features × weights) in neurons.
- Similarity Measures: In recommendation systems or NLP, dot products measure how similar two feature vectors are (e.g., user preferences vs. item features).
- Gradient Descent: Dot products appear in loss functions or when computing gradients.

### Python Implementation

Use NumPy’s np.dot() or @ operator for the dot product.

**Steps:**

- Import NumPy.
- Define two vectors of the same length as NumPy arrays.
- Compute the dot product using np.dot() or @.
- Display the result and interpret its meaning.

In [5]:
import numpy as np

# Step 1: Define two vectors of the same length
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Step 2: Compute the dot product
dot_product = np.dot(a, b)  # or use a @ b

# Step 3: Print the vectors and result
print("Vector a:", a)
print("Vector b:", b)
print("Dot Product (a · b):", dot_product)

# Step 4: Optional - Compute cosine similarity to show intuition
# Cosine similarity = (a · b) / (||a|| * ||b||)
norm_a = np.linalg.norm(a)  # Magnitude of a
norm_b = np.linalg.norm(b)  # Magnitude of b
cosine_similarity = dot_product / (norm_a * norm_b)
print("Cosine Similarity:", cosine_similarity)

Vector a: [1 2 3]
Vector b: [4 5 6]
Dot Product (a · b): 32
Cosine Similarity: 0.9746318461970762


---
---
## Project: Vector Similarity Checker

Input: Two lists of numbers (vectors).

Output: Their dot product and cosine similarity.



### How to Do It

- **Understand the Inputs:**

    - You’ll receive two lists of numbers (vectors) of the same length, e.g., [1, 2, 3] and [4, 5, 6].
    - These represent vectors in an n-dimensional space.

- **Dot Product:**

    - The dot product of two vectors $ \vec{a} $ and $ \vec{b} $ is calculated as:
$$\vec{a} \cdot \vec{b} = a_1 b_1 + a_2 b_2 + \dots + a_n b_n$$

    - It’s a scalar that measures how much the vectors align.
    - In Python, use np.dot() or the @ operator with NumPy arrays.

- **Cosine Similarity:**

    - Cosine similarity measures the cosine of the angle between two vectors, indicating how similar they are (regardless of magnitude):
$$\text{Cosine Similarity} = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\| \|\vec{b}\|}$$
where $ \|\vec{a}\| $ and $ \|\vec{b}\| $ are the Euclidean norms (magnitudes) of the vectors:
$$\|\vec{a}\| = \sqrt{a_1^2 + a_2^2 + \dots + a_n^2}$$

    - Output ranges from -1 (opposite directions) to 1 (same direction), with 0 indicating orthogonality (right angles).
    - In Python, compute the dot product and divide by the product of norms using np.linalg.norm().


- **Steps to Implement:**

    - Import NumPy for efficient vector operations.
    - Convert input lists to NumPy arrays.
    - Check if vectors have the same length (to avoid errors).
    - Compute the dot product.
    - Compute the cosine similarity using the dot product and vector norms.
    - Handle edge cases (e.g., zero vectors to avoid division by zero).

- **AI/ML Relevance:**

    - Dot products are used in neural networks for weighted sums.
    - Cosine similarity is common in NLP (e.g., comparing word vectors) and recommendation systems (e.g., user-item similarity).

In [9]:
import numpy as np

def vector_similarity_checker(vector1, vector2):
    # Todo 1: Convert input lists to NumPy arrays
    a = np.array(vector1)
    b = np.array(vector2)
    
    # Todo 2: Check if vectors have the same length
    if len(a) != len(b):
        raise ValueError('Vectors Must have the same lenght')
    
    # Todo 3: Compute the dot product
    dotProduct = np.dot(a, b)
    
    # Todo 4: Compute cosine similarity
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)

    if norm_a == 0 or norm_b == 0:
        raise ValueError('Cannot compute cosine similarity with zero vector')
    coisine_similarity = dot_product / (norm_a * norm_b)

    return dot_product, coisine_similarity


# Example usage
try:
    vector1 = [1, 2, 3]
    vector2 = [4, 5, 6]
    dot_prod, cos_sim = vector_similarity_checker(vector1, vector2)
    print(f"Vector 1: {vector1}")
    print(f"Vector 2: {vector2}")
    print(f"Dot Product: {dot_prod}")
    print(f"Cosine Similarity: {cos_sim:.4f}")
except ValueError as e:
    print(f"Error: {e}")

Vector 1: [1, 2, 3]
Vector 2: [4, 5, 6]
Dot Product: 32
Cosine Similarity: 0.9746
